### ISSUE TITLE
Doesn't seem to work on Mac with Iterm

### ISSUE THREAD

**Issue by kevinsimper** [tombh/texttop#14]
I am trying the quickstart and it does show the firefox launch screen, it does not respond to any input or clicks, neither keyboard shortcuts.

![image](https://cloud.githubusercontent.com/assets/1126497/19622959/c336f10e-98b7-11e6-9f21-8183359321ae.png)

What could I be doing wrong?

**Comment by tombh** [comment]
Sorry for the delay. I'm just waiting for a chance to get to play on a Mac to see what I can find.

**Comment by pahakalle** [comment]
@kevinsimper What shell are you using, try running it with bash, that worked for me

**Comment by mikew** [comment]
I'm able to zoom (with <kbd>⌃⇧+wheel</kbd> since <kbd>⌃+Wheel</kbd> is already taken by macOS), and click fine.

What doesn't work:
- Panning: Any sort of <kbd>⌃+Click</kbd> is already taken by macOS
- Keyboard Toggle: <kbd>⌃⌥M</kbd> does not work. Rather <kbd>⌃⌥M</kbd> followed by <kdb>⌃U</kbd> should zoom in, but it just opens FireFox's View Source (which is bound to <kdb>⌃U</kbd>)
- Exiting: <kbd>⌃⌥Q</kbd> does nothing

**Comment by tombh** [comment]
@mikew That's really useful info to have, thank you. I'm going to make sure the basic functionality is available on most terminals. Everyone should be able to use the keyboard and exit, but fancy mouse interaction will be a bonus.

**Comment by mikew** [comment]
Turns out iTerm does have an option that helps: In the Pointers section in Preferences there's an option "^-Click reported to apps, does not open menu".

With that enabled panning works, but everything else is the same. Zoom still needs ctrl+shift, keyboard toggle / quit shortcuts aren't working.

**Comment by tombh** [comment]
That's really good to know. I've been thinking that I should try to ditch as many modifier keys as possible and take a more mode based approach. Like for example `CTRL+B` switches into a mode where single keypresses do things. However the problem there is that I suspect almost all terminals will always automatically try to select text when you drag with the mouse - therefore we have to have some kind of modifier to enjoy the benefits of panning with a mouse.

**Comment by tombh** [comment]
I've switched to using tcell in the rewrite, which has much stricter keybinding setup. So we'll have to revisit these issues when the rewrite is published.

**Comment by ylluminate** [comment]
It appears that this is now resolved by simply checking "`Enable mouse reporting`" in the current iTerm 2 for the profile you wish to use it under:
![example](https://p153.p0.n0.cdn.getcloudapp.com/items/NQuBe9bq/edb3a7ed-3d2f-411b-9058-99969c2e6440.jpg?v=e61e855cbc2294de8c6e128a81527db0)
