### ISSUE TITLE
ERROR: unsatisfiable constraints: xdotool (missing)

### ISSUE THREAD

**Issue by lachesis** [tombh/texttop#15]
I'm trying to rebuild to make this work on my server with an Intel E5520 because I get "Illegal instruction" when running hiptext. I assume the build for that package uses some new features that my processor doesn't have. However, it looks like Alpine Linux has dropped xdotool?

```
fetch http://mirror1.hs-esslingen.de/pub/Mirrors/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://mirror1.hs-esslingen.de/pub/Mirrors/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
fetch http://mirror1.hs-esslingen.de/pub/Mirrors/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  xdotool (missing):
    required by: world[xdotool]
The command '/bin/sh -c apk add --no-cache bc xvfb ttf-dejavu xdotool@testing ffmpeg openssh mosh firefox dbus' returned a non-zero code: 1
```

**Comment by tombh** [comment]
Sorry for the delay. Thanks very much for this. I actually found the problem but haven't uploaded the fix yet. Basically Alpine had moved xdotool from testing.

**Comment by israellevin** [comment]
Is there a fix coming? Is there anything I can do to help?

**Comment by tombh** [comment]
I've pushed the branch I'm working on [`xdotool-fix`](https://github.com/tombh/texttop/tree/xdotool-fix).

However now there's a seemingly random bug where it crashes on some keypresses. I don't if it's connected to the fix - perhaps the fact that I now compile `xdotool` rather than use Alpine's own package.

Anyway, point is you can try switching to this new branch and running `docker build -t texttop .` as normal and you should be able to have a play until a random keypress crashes things. Or maybe you don't get the random crashes, let me know.

**Comment by shyukri** [comment]
I can still get the error locally:
```
Step 6/12 : RUN apk add --no-cache bc xvfb ttf-dejavu xdotool@testing ffmpeg openssh mosh firefox dbus
 ---> Running in 755c6733507f
fetch http://mirror1.hs-esslingen.de/pub/Mirrors/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://mirror1.hs-esslingen.de/pub/Mirrors/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
fetch http://mirror1.hs-esslingen.de/pub/Mirrors/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  xdotool (missing):
    required by: world[xdotool]
The command '/bin/sh -c apk add --no-cache bc xvfb ttf-dejavu xdotool@testing ffmpeg openssh mosh firefox dbus' returned a non-zero code: 1
```

**Comment by tombh** [comment]
I am in the middle of a complete rewrite. I've completely dropped the dependency on docker and everything inside that Dockerfile in fact. All you will need is a static Golang binary. So I'm afraid I'm just going to have to concentrate on the rewrite rather than fixing this :(

**Comment by shyukri** [comment]
Awesome, will watch it :)

**Comment by tombh** [comment]
Closing as I'll be releasing the rewrite soon.
