### ISSUE TITLE
Documentation (ELinks)

### ISSUE THREAD

**Issue by jfdhuiz** [tombh/texttop#17]
Your link to elinks is dead.

ELinks itself appears dead as well.

Consider the following:

- 1) Latest stable is 0.11.7 (22 August 2009; 8 years ago), latest preview is 0.12pre6 (30 October 2012; 5 years ago);
- 2) On 17 March 2017, OpenBSD removed ELinks from its ports tree, citing concerns with security issues and lack of responsiveness from the developers;
- 3) Some support for ECMAScript by using Mozilla's SpiderMonkey JavaScript engine;
- 4) SpiderMonkey surely had security fixes since 30 October 2012; 5 years ago;

5 years is a long time in software land. I don't think this software should be used anymore, by you or anyone else. I don't think this software should be recommended anymore. _If_ you recommend it, at least be clear about the above.

What I would recommend as alternative? I'm not aware of a CLI browser supporting JavaScript. Links removed their SpiderMonkey code from its tree because it was out of date.

Sources used: [Wikipedia](https://en.wikipedia.org/wiki/ELinks)

**Comment by tombh** [comment]
That's really helpful context, thank you. So what I've done is actually just replace the link to this issue!

**Comment by hjpotter92** [comment]
There is also [Lynx](https://lynx.browser.org)

**Comment by mycaule** [comment]
And [w3m](https://en.wikipedia.org/wiki/W3m) which is quite popular too.

**Comment by AcidCaos** [comment]
Link to the (archived) original elinks website:
https://web.archive.org/web/20170619063608/http://www.xteddy.org/elinks/
New link: 
http://elinks.or.cz/

**Comment by OliverLew** [comment]
new link:
https://github.com/rkd77/elinks
