### ISSUE TITLE
docker is difficult to install

### ISSUE THREAD

**Issue by MaxPleaner** [tombh/texttop#2]
If you can remove the docker dependency #ThatWouldBeGreat

I've tried to install it on two platforms now (my Ubuntu Chroot on a SD card and my Nitrous.io box), neither work. It always says docker: `Cannot connect to the Docker daemon. Is the docker daemon running on this host?.` 

The reason I'm posting this issue is that I'm genuinely excited about this project and have been wondering for a while whether something is possible.

**Comment by gravcat** [comment]
You may have installed an outdated version of Docker via your apt repository. Check the official Docker documentation for proper installation.

**Comment by tombh** [comment]
I suspect it will be far easier to debug the docker issue than try and get texttop running without docker. Maybe you need to `systemctl start docker` or similar?

Texttop depends on a lot of things
  * Golang
  * X dev libs
  * patched version of hiptext
  * ffmpeg v3

It's easier to support just docker, than having to support installing all the above on different platforms.

**Comment by MaxPleaner** [comment]
OK thanks for the encouragement, will try again. I realize that this isn't
really an issue with Texttop and that generally Docker installs without
issues, but I got kinda stuck so I figured I'd reach out to some smart
people.

**Comment by colemickens** [comment]
Did you add your user to the `docker` group? You'll get that error if your user doesn't have permission to talk to the docker socket.
