### ISSUE TITLE
Doubts on how to use, can't run it successfully

### ISSUE THREAD

**Issue by compilerhemant** [tombh/texttop#20]
I issued the following command on the server

    docker pull tombh/texttop

After that The following commands on server

    docker run -d \
      -p 7777:7777 -p 60000-60020:60000-60020/udp \
      -v ${HOME}/.ssh:/root/.ssh:ro \
      tombh/texttop

Everything worked fine with no errors on the server so far

After issuing the following commands on the terminal of the local machine, it keeps on watitng for input with no error message or prompt

    mosh --ssh="ssh -p 7777" user@yourserver

I wrote the following commands

    cd /app
    ./run.sh

Still no response from the server, Can you please tell me what I am doing wrong

Although I am able to ssh into the server with the normal ssh command.

**Comment by tombh** [comment]
Normal `ssh` is really exactly the same, other than it's a bit slower. So just stick with that. Also try using a different terminal. What terminal did you try this with?
