### ISSUE TITLE
Will Browsh support browsers other than Firefox?

### ISSUE THREAD

**Issue by tobimensch** [tombh/texttop#21]

**Comment by tombh** [comment]
Yes.

I've been writing with the aim to support all browsers that implement the webextensions API. For now I'm just focussing on Firefox as that's my default browser. Some notes to consider for fully implementing this.

  * Chrome doesn't support extensions in headless mode! So we need to find a way to stop Chrome stealing focus on things like window resizing. Only relevant if using Browsh locally of course.
  * Chrome also has a different API for snapshoting the rendered tab.
  * Firefox still doesn't have support for the standardised RDP. It'd be nice to not have to rewrite the RDP commands for every browser. Although theoretically the RDP commands should be minimal, eg; resizing the browser window and automatically installing the extension.

**Comment by tobimensch** [comment]
@tombh
Thanks!

How far has the development of Browsh progressed?

**Comment by tombh** [comment]
Well it's actually currently usable, just need to improve the performance and features. The current release has a bug where commas mess up the rendering, but current HEAD of `webext-rewrite` has that fixed. So you can browse like 90% of websites, scroll pages, click with the mouse, even watch Youtube and draw lines on those sketch paint app things. There's only 1 tab at the moment as well. So it's not ready for general release yet, but I'm definitely starting to feel like I need some testers. My current focus is getting the whole CI process running smoothly, so new features are taking a back seat.

**Comment by tobimensch** [comment]
@tombh 
Thanks!

I've a VPS with Chromium 57.0.2987.98 . Will that work?

I hope you'll release Browsh soon, because I'm stuck with slow internet currently.

**Comment by tombh** [comment]
This is literally seconds hot off the press: `docker run --rm -it tombh/texttop:v0.2.5`

Do you know about Docker? I don't expect this to be the main installation method, as the download is so big, perhaps about 800MB. But it is handy for quickly getting up and running. So that command above is literally all you need to run (it will automatically download the docker image on first run) and you should have the Google home page. `CTRL+l` to focus the URL bar, `CTRL+q` to quit, arrow keys to scroll, mouse clicks work.

This is still a very early release, so don't expect too much :/

**Comment by tobimensch** [comment]
@tombh 
I need to install it without docker. My VPS can't run anything newer than Debian Jessie and docker doesn't work properly in it. I'm also stuck to an outdated kernel there, which might be the reason.

**Comment by tombh** [comment]
Ah right. Ok I have one last thing but it's not ready yet and don't want to make public yet. Email me (tombh.co.uk, tom@) and I'll let you know when it's ready, will be good to get your feedback too.

**Comment by tombh** [comment]
Closing for #27 instead.
