### ISSUE TITLE
Strange glyphs in normal Firefox after starting browsh

### ISSUE THREAD

**Issue by toXel** [tombh/texttop#22]
First: Thank you for this nice project!

I wanted to try it and installed the v0.2.5 Arch Linux package. I already have Firefox 58.0.1 installed. So I started browsh and got this output:
```
Starting Browsh...
Starting...
```
Then it exited with error code 1. I then tried to start my normal Firefox again and now I get this glyphs instead of a normal font:
![screenshot from 2018-02-02 20-10-25](https://user-images.githubusercontent.com/2300709/35750415-316ac8a4-0855-11e8-94fb-e52e3e30549c.png)

They're even there after a reboot.

**Comment by tombh** [comment]
Gosh, that's an embarrassing oversight on my part. Really sorry. You can just uninstall a new extension you'll discover in `about:addons`, it's called 'browsh'. I'll get on a fix as well right a way so you can send me some debug output then as well.

**Comment by tombh** [comment]
I've released a new version: https://github.com/tombh/texttop/releases/tag/v0.2.6

It uses its own profile now, so won't conflict with an existing Firefox setup. Also you can now run it with the `-debug` flag so it will output logs to the directory within which the command was run.

**Comment by toXel** [comment]
Hey thanks for the fast answer! I didn't know that Browsh installs an extension. Then I would've found it by myself 😉  maybe I should read more before I try out experimental stuff next time 😁 .
With the new version it now also works. So I think it was a problem with my current Firefox profile. Maybe an extension or something?

**Comment by tombh** [comment]
I think that existing profiles are just a minefield of compatibility issues, so it was great that you ran into the problem because it got me to sort it out properly - by using a dedicated Browsh profile. And wow that's great that it works now. Can you tell me your terminal app? And how good the graphics rendering is? Like are the character block fonts aligned properly? Is there any banding? Maybe send a screenshot?

**Comment by return-misaPuding** [comment]
I know this can be resolved simply by disabling the browsh extension, but why does this happen? does browsh really need the browser to not display text in order to function?
