### ISSUE TITLE
Loading https://www.welt.de causes a screenshot failure

### ISSUE THREAD

**Issue by tombh** [tombh/texttop#50]
Relevant log message:
`["_getPixelData@moz-extension://a268f53e-0352-4b9c-815c-cf1d00d4c150/content.js:18180:12\n_getScreenshot@moz-extension://a268f53e-0352-4b9c-815c-cf1d00d4c150/content.js:18133:12\n_getScreenshotWithText@moz-extension://a268f53e-0352-4b9c-815c-cf1d00d4c150/content.js:18075:29\ngetScreenshotWithText/&lt;@moz-extension://a268f53e-0352-4b9c-815c-cf1d00d4c150/content.js:18058:7\nlogPerformance@moz-extension://a268f53e-0352-4b9c-815c-cf1d00d4c150/content.js:17228:5\ngetScreenshotWithText@moz-extension://a268f53e-0352-4b9c-815c-cf1d00d4c150/content.js:18057:5\nsendRawText@moz-extension://a268f53e-0352-4b9c-815c-cf1d00d4c150/content.js:18261:5\nsendRawText@moz-extension://a268f53e-0352-4b9c-815c-cf1d00d4c150/content.js:17372:5\n_setupMode@moz-extension://a268f53e-0352-4b9c-815c-cf1d00d4c150/content.js:17572:7\n_handleBackgroundMessage@moz-extension://a268f53e-0352-4b9c-815c-cf1d00d4c150/content.js:17528:9\n_listenForBackgroundMessages/&lt;@moz-extension://a268f53e-0352-4b9c-815c-cf1d00d4c150/content.js:17483:9\n"]`

**Comment by tobimensch** [comment]
Thanks for looking into it!

**Comment by tobimensch** [comment]
Can confirm this works now. Thanks a bunch!
