### ISSUE TITLE
Firefox ESR not detected

### ISSUE THREAD

**Issue by ZafotheNinja** [tombh/texttop#55]
Hey, trying to install on Debian 8, got the package to install but it says it requires "Firefox" as a dependency. I have Firefox esr installed but Browsh does not recognize it. 

I could install the latest Firefox, but I would prefer not to risk making a Franken-Debian if at all possible. (The latest is only in the unstable 'Sid' branch)

Thanks for your time.

**Comment by tombh** [comment]
Ah yeah, was going to suggest Docker. So did you get it working? You're using the `webext-rewrite` branch right?

**Comment by ZafotheNinja** [comment]
Well, I thought installing docker would be a simple matter, but it is giving me a "Permission Denied" on a root account lol. Time to hit the docs I guess.

**Comment by tombh** [comment]
Ah I didn't specify in the docs that you need to use the tagged version of the Docker image, so `docker run tombh/texttop:v1.1.4`

It's all a bit confusing at the moment, because I haven't officially released Browsh to the master branch yet.
