### ISSUE TITLE
Installed properly but not working for me. Any missing step? 

### ISSUE THREAD

**Issue by farsighter** [tombh/texttop#6]
Hi,
I found this project interesting but unfortunately couldn't get it to work 

Yesrerday I setup everything on my Debian 8 Xen VPS exactly as described without any installation error.

( First, when I tried to run it directly on VPS I got an error 'Bad signal name "-" ' on Docker shell - but I understand it's not designed to work this way. )

When I tried to connect using MobaXterm (as Mosh client for Windows) I got an error which said something like "not working ..Is SSH proxycommand enabled? "

I suspect problem has something to do with port forwarding part which blocks my Mosh access to the Docker container. (no firewall on that fresh VPS I was using). 

I'm no way an expert with Docker, maybe some additional settings are required apart from those commands provided in description?

Thank you for any help

**Comment by tombh** [comment]
The ` 'Bad signal name "-" '` makes me think you've hit the CPU arch bug. The workaround is to build the docker image your self, in this case on your VPS. Try this;
```
git clone https://github.com/tombh/texttop.git
cd texttop
docker build -t texttop .
```
And then run the image;
```
docker run --rm -it -d \
  -p 7777:7777 -p 60000-60020:60000-60020/udp \
  -v ~/.ssh/authorized_keys:/root/.ssh/authorized_keys \
  texttop
```

**Comment by farsighter** [comment]
I did that but still getting same errors.

When I'm trying to run it directly on VPS here is output:

root@server:~/texttop# docker run --rm -it texttop sh
/app # ./run.sh
sh: bad signal name '-'


When I'm trying to Mosh into it from another VPS here is output:

root@contea:~# mosh root@myserver:7777 
/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).

I don't know why I'm getting those errors after carefully following instructions :(

**Comment by farsighter** [comment]
It's OK now .
I tested on a different VPS (KVM) and it's working . 
That probably was a problem with the other VPS (maybe 512MB RAM too low for that?) 

Thanks

**Comment by tombh** [comment]
Ah great! I've had success with 512MB, but it's a bit slow, it is running X and Firefox after all.

If you get a chance, it would be good to see the logs from the container at `/app/logs`.
