### ISSUE TITLE
What to do about TTY resizing?

### ISSUE THREAD

**Issue by tombh** [tombh/texttop#8]
It'd be good if you could dynamically resize your terminal, because: 
1. It's just convenient when rearranging your windows.
2. You get an increase in resolution when the TTY is bigger.
3. You get a reduction in bandwidth when the TTY is smaller.

The main obstacle I see is how to negotiate the dimensions with `Xvfb`. When texttop first starts it assumes a desktop width of 1200 and decides the height depending on the TTY width/height ratio. So `Xvfb` is locked into that resolution and `xrandr` (which can dynamically resize the desktop) doesn't work with `Xvfb`, besides it would be clunky anyway I reckon. Also those desktop dimensions are passed onto `ffmpeg`, so it knows which part of the desktop to stream.

So. My first thought is just to retain this initial size and aspect ratio for the duration of the session. If the TTY size changes then scaling can happen but the aspect ratio is static. The only downside is that it's then possible to have large, unused areas of the TTY.

**Comment by Oblomov** [comment]
I wonder if using Xdummy instead of Xvfb (like xpra does) would help in this sense? IIRC it supports RandR

**Comment by tombh** [comment]
Oh, I didn't know that about Xdummy, thanks. Though I'm actually completely dropping X in the rewrite. I'm going to be restricting this project to just webextension-compatible browsers, so then I can use the DOM Canvas to generate the TTY blocks.

**Comment by Oblomov** [comment]
I guess that makes sense if your only intent is to allow “remote browsing” as opposed to having a full-fledged X session (after all, there's already xpra for that ;-)).

I'll take the opportunity to mention [the SIXEL protocol](https://github.com/saitoha/libsixel) while we're at it then. Maybe you can generate _that_ on the browser side, might be more compact to stream.

**Comment by tombh** [comment]
Yes, I just want focus on remote browsing, mainly just because that was actually my original use case and also because by doing so I can know overlay actual text characters, which takes it from gimmick to something practical.

I've looked into sixel, but I just don't think it has wide enough adoption and also, as you say, we already have so many low-bandwidth VNC-esque projects like XPRA, that implementing sixel wouldn't feel that unique.

**Comment by tombh** [comment]
Closing as resizing is fully supported in the rewrite
